version: "3"

services:
  server:
    image: node:16
    ports:
      - "8080:8080"
    command: ./server/server.sh
    volumes:
      - ./server:/server
  db:
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./db:/db
